name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add MrBeastify
        run: |
          git submodule add https://github.com/leminlimez/MrBeastify.git Tweaks/MrBeastify
          git add .
          git commit -m "added MrBeastify submodule"
          git push origin

      - name: Make .bundle files
        run: |
          cd Bundles
          ln -s ../Tweaks/MrBeastify/layout/Library/Application\ Support/MrBeastify.bundle MrBeastify.bundle
          git add .
          git commit -m "Added submodule bundle"
          git push origin

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote Tweaks/Alderis
          git add .
          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
          git add .
          git submodule update --init --recursive --remote Tweaks/MrBeastify
          git add .
          git submodule update --init --recursive --remote Tweaks/PSHeader
          git add .
          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
          git add .
          git submodule update --init --recursive --remote Tweaks/YTABConfig
          git add .
          git submodule update --init --recursive --remote Tweaks/YTNoCommunityPosts
          git add .
          git submodule update --init --recursive --remote Tweaks/YTUHD
          git add .
          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
          git add .
          git submodule update --init --recursive --remote Tweaks/YouMute
          git add .
          git submodule update --init --recursive --remote Tweaks/YouPiP
          git add .
          git submodule update --init --recursive --remote Tweaks/YouQuality
          git add .
          git submodule update --init --recursive --remote Tweaks/YouTubeHeader
          git add .
          git submodule update --init --recursive --remote Tweaks/iSponsorBlock
          git add .
          git commit -m "updated submodules"
          git push origin
        continue-on-error: true

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
